language: node_js
node_js:
  - "stable"
cache:
  directories:
  - ./client/node_modules
script:
  - npm run heroku-postbuild
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master